/**
 * ImageKit Media Upload / Delete
 *
 * Env vars (Vite):
 *   VITE_IMAGEKIT_PRIVATE_KEY   — IK private key  (⚠️ move to server-side auth in prod)
 *   VITE_IMAGEKIT_URL_ENDPOINT  — e.g. https://ik.imagekit.io/your_id
 *
 * When env vars are absent (demo mode) the upload simulates progress and returns
 * a temporary object URL so the UI still works without a real account.
 */

export type MediaItem = {
  id: string;
  /** "image" or "video" */
  type: "image" | "video";
  /** Public URL (ImageKit CDN or blob: in demo mode) */
  url: string;
  /** ImageKit file ID — used for deletion */
  fileId?: string;
  /** For videos: thumbnail URL (auto-generated by IK) */
  thumbnailUrl?: string;
  caption?: string;
  uploadedAt: string;
};

const IK_PRIVATE_KEY    = import.meta.env.VITE_IMAGEKIT_PRIVATE_KEY  ?? "";
const IK_URL_ENDPOINT   = import.meta.env.VITE_IMAGEKIT_URL_ENDPOINT ?? "";
const IK_UPLOAD_URL     = "https://upload.imagekit.io/api/v1/files/upload";
const IK_API_URL        = "https://api.imagekit.io/v1";

function ikAuthHeader(): string {
  return `Basic ${btoa(`${IK_PRIVATE_KEY}:`)}`;
}

export function isImageKitConfigured(): boolean {
  return IK_PRIVATE_KEY.length > 0 && IK_URL_ENDPOINT.length > 0;
}

function sleep(ms: number) {
  return new Promise<void>((r) => setTimeout(r, ms));
}

/**
 * Upload a File to ImageKit (or simulate for demo mode).
 * @param file       File selected by the user
 * @param folder     ImageKit folder path (default "/zen-hub")
 * @param onProgress Callback with 0-100 progress value
 */
export async function uploadMedia(
  file: File,
  folder = "/zen-hub",
  onProgress?: (pct: number) => void,
): Promise<MediaItem> {
  const isVideo = file.type.startsWith("video/");
  const demoId  = `demo_${Date.now()}_${Math.random().toString(36).slice(2)}`;

  // ── Demo mode: simulate progress + use object URL ────────────────────────
  if (!isImageKitConfigured()) {
    if (onProgress) {
      onProgress(20); await sleep(150);
      onProgress(55); await sleep(200);
      onProgress(85); await sleep(150);
      onProgress(100);
    }
    const url = URL.createObjectURL(file);
    return {
      id: demoId,
      type: isVideo ? "video" : "image",
      url,
      thumbnailUrl: isVideo ? undefined : url,
      uploadedAt: new Date().toISOString(),
    };
  }

  // ── Real ImageKit upload via XHR (supports progress) ────────────────────
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    const body = new FormData();
    body.append("file", file);
    body.append("fileName", `${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`);
    body.append("folder", folder);
    body.append("useUniqueFileName", "true");

    if (onProgress) {
      xhr.upload.onprogress = (e) => {
        if (e.lengthComputable) onProgress(Math.round((e.loaded / e.total) * 92));
      };
    }

    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        if (onProgress) onProgress(100);
        const d = JSON.parse(xhr.responseText);
        // For videos, IK auto-generates a thumbnail at /tr:so-2,h-300,w-400,f-jpg
        const thumbPath = isVideo
          ? `${IK_URL_ENDPOINT}/tr:so-2,h-300,w-400,f-jpg/${d.filePath}`
          : undefined;
        resolve({
          id:           d.fileId,
          type:         isVideo ? "video" : "image",
          url:          d.url,
          fileId:       d.fileId,
          thumbnailUrl: thumbPath,
          uploadedAt:   new Date().toISOString(),
        });
      } else {
        reject(new Error(`ImageKit upload failed (${xhr.status})`));
      }
    };

    xhr.onerror = () => reject(new Error("Network error during upload"));
    xhr.open("POST", IK_UPLOAD_URL);
    xhr.setRequestHeader("Authorization", ikAuthHeader());
    xhr.send(body);
  });
}

/** Delete a file from ImageKit by its fileId. No-op for demo items. */
export async function deleteMedia(fileId?: string): Promise<void> {
  if (!fileId || fileId.startsWith("demo_") || !isImageKitConfigured()) return;
  try {
    await fetch(`${IK_API_URL}/files/${fileId}`, {
      method:  "DELETE",
      headers: { Authorization: ikAuthHeader() },
    });
  } catch {
    // silently ignore deletion errors
  }
}
