import { SvgAreaChart } from "../../components/shared/CssCharts";
import { useState } from "react";
import { useParams, useNavigate } from "react-router";
import {
  ArrowLeft, Star, Users, CalendarDays, Banknote, CheckCircle, MessageSquare,
  Clock, BarChart2, CircleDollarSign, Wallet, TrendingUp, Mail, Phone, Percent,
} from "../../components/shared/icons";
import { useAuth } from "../../context/AuthContext";
import { usePageData } from "../../hooks/usePageData";
import { useFinancial } from "../../context/FinancialContext";

export default function CompanyTherapistDetail() {
  const { therapistId } = useParams<{ therapistId: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const { company, therapists, therapies, sessionRecords, therapistStore: store,
    mutateMarkCommissionPaid } = usePageData();
  // FinancialContext: auto-inject commission payment as "saída" — same pattern used
  // by CompanyCommissions.tsx. Without this the payment mark was persisted but no
  // financial transaction was created, making the cash-flow dashboard unaware of it.
  const { addTransaction } = useFinancial();

  // ── Hooks must all be declared before any conditional return ──────────────
  const [paying, setPaying] = useState(false);

  const therapist = therapists.find((t) => t.id === therapistId);
  const therapistRecords = (sessionRecords as any[]).filter((r) => r.therapistId === therapistId);
  const primaryColor = company?.color || "#0D9488";

  if (!therapist) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-center">
        <BarChart2 className="w-10 h-10 mx-auto mb-3 text-gray-200" />
        <p className="text-gray-500">Terapeuta não encontrado.</p>
        <button onClick={() => navigate(-1)} className="mt-4 text-sm underline" style={{ color: primaryColor }}>
          Voltar
        </button>
      </div>
    );
  }

  const assoc = store.getAssociation(therapist.id);
  // Use the real Firestore commission value from the therapist document.
  // Fall back to the in-memory store only if the Firestore field is absent
  // (legacy demo compatibility), but never let a stale mock override a real value.
  const rate = therapist.commission ?? assoc.commission ?? 50;

  // Compute earnings split by paid status
  const paidRecords   = therapistRecords.filter((r: any) => r.paidByCompany === true);
  const unpaidRecords = therapistRecords.filter((r: any) => r.paidByCompany !== true);

  const totalEarned   = therapistRecords.reduce((s: number, r: any) => s + (r.therapistEarned || 0), 0);
  const totalPaid     = paidRecords.reduce((s: number, r: any) => s + (r.therapistEarned || 0), 0);
  const totalReceivable = unpaidRecords.reduce((s: number, r: any) => s + (r.therapistEarned || 0), 0);
  const totalGross    = therapistRecords.reduce((s: number, r: any) => s + (r.totalCharged || 0), 0);
  const companyShare  = totalGross - totalEarned;

  const handlePayAll = async () => {
    if (unpaidRecords.length === 0) return;
    setPaying(true);
    await mutateMarkCommissionPaid(unpaidRecords.map((r: any) => r.id as string));
    // Register as outflow in the financial dashboard
    await addTransaction({
      type: "saida",
      category: "comissoes",
      description: `Comissão – ${therapist.name}`,
      amount: totalReceivable,
      date: new Date().toISOString().split("T")[0],
      paymentMethod: "Transferência",
      autoGenerated: true,
      notes: `${unpaidRecords.length} sessão(ões) · ${rate}% de comissão`,
    });
    setPaying(false);
  };

  // Monthly aggregated chart data from session records
  const monthMap: Record<string, { sessions: number; gross: number; net: number }> = {};
  therapistRecords.forEach((r: any) => {
    const m = r.date ? r.date.substring(0, 7) : "—";
    if (!monthMap[m]) monthMap[m] = { sessions: 0, gross: 0, net: 0 };
    monthMap[m].sessions++;
    monthMap[m].gross += r.totalCharged || 0;
    monthMap[m].net += r.therapistEarned || 0;
  });
  const history = Object.entries(monthMap).map(([month, v]) => ({
    month: new Date(month + "-01T12:00:00").toLocaleDateString("pt-BR", { month: "short", year: "2-digit" }),
    ...v,
  }));

  const therapistTherapyList = therapies.filter((t) => therapist.therapies?.includes(t.id));

  return (
    <div className="space-y-6">
      {/* Back nav */}
      <button
        onClick={() => navigate(-1)}
        className="flex items-center gap-2 text-sm text-gray-500 hover:text-gray-800 transition-colors group"
      >
        <ArrowLeft className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform" />
        Voltar para Comissões
      </button>

      {/* Profile header */}
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="h-3" style={{ background: `linear-gradient(90deg, ${primaryColor}, ${primaryColor}60)` }} />
        <div className="p-6">
          <div className="flex items-start gap-5 flex-wrap">
            <div className="relative shrink-0">
              {therapist.avatar ? (
                <img src={therapist.avatar} alt={therapist.name} className="w-24 h-24 rounded-2xl object-cover border-4 border-white shadow-md" />
              ) : (
                <div className="w-24 h-24 rounded-2xl border-4 border-white shadow-md flex items-center justify-center text-white text-3xl" style={{ background: primaryColor }}>
                  {therapist.name.charAt(0)}
                </div>
              )}
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-3 flex-wrap">
                <h2 className="text-gray-900">{therapist.name}</h2>
                <span className="flex items-center gap-1 px-2.5 py-1 rounded-xl text-white text-xs" style={{ background: primaryColor, fontWeight: 700 }}>
                  <Percent className="w-3 h-3" /> {rate}% comissão
                </span>
              </div>
              <p className="text-gray-500 text-sm mt-0.5">{therapist.specialty}</p>
              <div className="flex items-center gap-1 mt-2">
                {[1,2,3,4,5].map((s) => (
                  <Star key={s} className={`w-3.5 h-3.5 ${s <= Math.floor(therapist.rating ?? 0) ? "fill-yellow-400 text-yellow-400" : "text-gray-200 fill-gray-200"}`} />
                ))}
                <span className="text-sm text-gray-700 ml-1" style={{ fontWeight: 700 }}>{therapist.rating ?? "—"}</span>
                <span className="text-xs text-gray-400">· {therapist.totalSessions ?? 0} sessões</span>
              </div>
              <div className="flex flex-wrap gap-3 mt-3">
                <a href={`mailto:${therapist.email}`} className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-gray-700">
                  <Mail className="w-3.5 h-3.5" /> {therapist.email}
                </a>
                <a href={`tel:${therapist.phone}`} className="flex items-center gap-1.5 text-xs text-gray-500 hover:text-gray-700">
                  <Phone className="w-3.5 h-3.5" /> {therapist.phone}
                </a>
              </div>
              <div className="flex flex-wrap gap-1.5 mt-3">
                {therapistTherapyList.map((th) => (
                  <span key={th.id} className="text-xs px-2 py-0.5 rounded-full text-white" style={{ background: th.color }}>
                    {th.name}
                  </span>
                ))}
              </div>
            </div>
            <div className="flex flex-col gap-2 shrink-0">
              <button
                onClick={handlePayAll}
                disabled={paying || unpaidRecords.length === 0}
                className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-white text-sm disabled:opacity-60 transition-opacity"
                style={{ background: primaryColor, fontWeight: 600 }}
              >
                <Banknote className="w-4 h-4" />
                {paying ? "Pagando..." : unpaidRecords.length === 0 ? "Tudo pago ✓" : "Pagar comissão"}
              </button>
              <button className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-gray-200 text-gray-600 text-sm hover:bg-gray-50 transition-colors">
                <MessageSquare className="w-4 h-4" /> Enviar mensagem
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* KPI cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          {
            label: "A receber",
            value: `R$ ${totalReceivable.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`,
            sub: `${unpaidRecords.length} sessão${unpaidRecords.length !== 1 ? "ões" : ""} pendente${unpaidRecords.length !== 1 ? "s" : ""}`,
            icon: Wallet, color: totalReceivable > 0 ? "#F59E0B" : "#059669",
          },
          {
            label: "Já pago",
            value: `R$ ${totalPaid.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`,
            sub: `${paidRecords.length} sessão${paidRecords.length !== 1 ? "ões" : ""} liquidada${paidRecords.length !== 1 ? "s" : ""}`,
            icon: CheckCircle, color: "#059669",
          },
          {
            label: "Receita gerada",
            value: `R$ ${totalGross.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`,
            sub: "bruto total",
            icon: TrendingUp, color: primaryColor,
          },
          {
            label: "Empresa retém",
            value: `R$ ${companyShare.toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`,
            sub: `${100 - rate}%`,
            icon: CircleDollarSign, color: "#6B7280",
          },
        ].map((s) => (
          <div key={s.label} className="bg-white rounded-xl border border-gray-100 p-5 shadow-sm">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center mb-3" style={{ background: `${s.color}18` }}>
              <s.icon className="w-4 h-4" style={{ color: s.color }} />
            </div>
            <p className="text-gray-400 text-xs">{s.label}</p>
            <p className="text-xl text-gray-900 mt-0.5" style={{ fontWeight: 700 }}>{s.value}</p>
            <p className="text-xs text-gray-400 mt-0.5">{s.sub}</p>
          </div>
        ))}
      </div>

      {/* Chart */}
      {history.length > 0 && (
        <div className="bg-white rounded-xl border border-gray-100 p-6 shadow-sm">
          <h3 className="text-gray-900 mb-4">Evolução de Ganhos</h3>
          <SvgAreaChart
            data={history}
            valueKey="net"
            labelKey="month"
            color="#10B981"
            height={200}
            formatY={(v) => `R$${v >= 1000 ? (v / 1000).toFixed(1) + "k" : v.toFixed(0)}`}
          />
        </div>
      )}

      {/* Recent sessions */}
      <div className="bg-white rounded-xl border border-gray-100 p-6 shadow-sm">
        <h3 className="text-gray-900 mb-4">Últimas Sessões</h3>
        {therapistRecords.length === 0 ? (
          <p className="text-xs text-gray-400 text-center py-8 italic">Nenhuma sessão registrada.</p>
        ) : (
          <div className="space-y-2">
            {therapistRecords.slice(0, 10).map((r: any) => (
              <div key={r.id} className="flex items-center gap-3 p-3 rounded-xl bg-gray-50">
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${r.paidByCompany ? "bg-emerald-100" : "bg-white border border-gray-200"}`}>
                  {r.paidByCompany
                    ? <CheckCircle className="w-3.5 h-3.5 text-emerald-500" />
                    : <Clock className="w-3.5 h-3.5 text-gray-400" />
                  }
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm text-gray-900 truncate" style={{ fontWeight: 600 }}>{r.clientName}</p>
                  <p className="text-xs text-gray-500">{r.therapyName} · {r.duration}min · {r.date}</p>
                </div>
                <div className="text-right shrink-0">
                  <p className="text-sm text-emerald-600" style={{ fontWeight: 700 }}>+R$ {(r.therapistEarned || 0).toFixed(2)}</p>
                  <p className={`text-xs ${r.paidByCompany ? "text-emerald-500" : "text-amber-500"}`}>
                    {r.paidByCompany ? "✓ Pago" : "Pendente"}
                  </p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}